### ISSUE TITLE
Make sidebar urls relative

### ISSUE THREAD

**Issue by ucalyptus2** [explore-ml-iemk/explore-ml-iemk.github.io#9]
- Info abt this ticket has been conveyed on Discord.

**Comment by ucalyptus2** [comment]
@Fork-chan any updates?

**Comment by Dsantra92** [comment]
@forkbabu I believe we are looking on the wrong side of things. Once deployed, the URLs are working just fine, I believe there is some trick i.e. extrac options used during the `bundle exec jekyll serve` like mentioning the whole url or somethings like that. So I think this issue should be closed for now.
